# -*- coding: utf-8 -*-
"""quake_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Y1LFQ-asxuIukoRc9Diwg-XBo9I3eAa
"""

import numpy as np

def generate_signal(mag=5.0, noise_level=0.5, length=300):
    t = np.linspace(0, 5, length)
    noise = np.random.normal(0, noise_level, length)

    # earthquake intensity
    eq_wave = np.sin(30 * t) * (mag/8.0)
    eq_wave[t < 1.0] = 0   # no quake before P-wave

    return noise + eq_wave