# -*- coding: utf-8 -*-
"""quake_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA48hzNSCS9Nvh_8b769O5cikGdYP-HZ
"""

import numpy as np

def generate_signal(mag=5.0, noise_level=0.5, length=300):
    t = np.linspace(0, 5, length)

    # Stronger real-like noise
    noise = np.random.normal(0, noise_level * (1 + mag*0.15), length)

    # P-wave (small, fast)
    p_wave = 0.6 * np.sin(40 * t) * (mag * 1.2)

    # S-wave (strong, after P-wave)
    s_wave = np.sin(18 * t) * (mag * 2.8)
    s_wave[t < 1.0] = 0

    # Surface wave (strongest)
    surface = np.sin(5 * t) * (mag * 4.0)
    surface[t < 1.8] = 0

    return noise + p_wave + s_wave + surface